### ISSUE TITLE
Add More in Data Entry

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/documentation-wiki#132]
When adding a Parts Attribute, is it necessary to include a part name?  "Location" of specimen was set up under Parts Attribute "add more."  When I click on "add specimen part" I get this screen:
![image](https://user-images.githubusercontent.com/43214224/66236982-78b55a00-e6b9-11e9-914c-445b2a7b6a5a.png)
"Attribute Type" has "location" and the" Value" is the location where the specimen is stored.  The actual part name was recorded in the main "parts" grid.  Does it have to be entered in the "add more" grid as well?   Thanks.

**Comment by mbprondzinski** [comment]
Is it possible to add "specimen" to the code table "ctspecimen_part_name"?  I am using "specimen" for my rock/mineral samples, in order to add specimen parts location (storage).  Or maybe "geosample"?  I need something generic for my geo specimens.

**Comment by Jegelewicz** [comment]
I like geosample. @Nicole-Ridgwell-NMMNHS thoughts?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I think geological sample or geosample would be fine. The following could probably also eventually be added:
geological sample, polished
geological sample, thin section

**Comment by mbprondzinski** [comment]
I'm not sure what the reference is telling me.  I created the "part extras" as told to by Dusty way back when.  I still can't edit the part "location" without re-entering the part/extras manually.

**Comment by Jegelewicz** [comment]
>  I still can't edit the part "location" without re-entering the part/extras manually.

The "extras" aren't loaded. Go to Enter Data>Bulkloader>Extras for Loaded Specimens

Once these are loaded through the part bulkload tool, then you will be able to edit the locations.

**Comment by mbprondzinski** [comment]
Actually, Teresa, they’ve been loaded and reloaded.  They weren’t validated by me because the “geosample” part name wasn’t valid…which I was well aware of.  The “edit extras” is documented in Arctos, which I read and reread and accessed through the “browse and edit extras”, but could not get it to work.  Now I can see I will have to re-enter the “extras” (again) because the part name is still coming up “invalid” and the catalogued item is also “invalid.”

**Comment by Jegelewicz** [comment]
Mary Beth,

You need to load the specimen record before you can load any "extras".

You haven't loaded the specimen records because I can still see them in the staging table:
![image](https://user-images.githubusercontent.com/5725767/67787220-cf525180-fa35-11e9-9777-05d680fff036.png)

Go to Data Entry>Bulkloader>Browse and Edit. Filter by your Arctos user name and then select "Mark to Load". Once the records are loaded, you will be able to load/edit the extras.

**Comment by mbprondzinski** [comment]
If the extras weren’t valid to begin with, would I still have been able to load the specimen records?  I’ve been waiting on the part name!  Why is that still “invalid”?

**Comment by campmlc** [comment]
Hi Mary Beth,
The first step, loading the specimen record, was originally hung up because
the part name "geosample" wasn't yet in the code table. That should be
fixed. . . assuming that is so, you need to mark all your records in the
regular bulkloader (Bulkloader, Browse and Edit, choose your name or
accession) to load. Once they have loaded, you have to go back to the
Bulkloader, go down below browse and edit to Extras, and mark those to
load. The extras can't load until the specimen record exists as a catalog
record in Arctos - e.g. no longer in the bulkloader table.

**Comment by Jegelewicz** [comment]
I can see the extras and they should load once the records load because geosample is a part now.

**Comment by mbprondzinski** [comment]
Okay, thanks Mariel.  I “marked all to load.”  I guess I will be notified when they have loaded.

**Comment by mbprondzinski** [comment]
People who try to do this stuff on their own are dangerous!!!

**Comment by mbprondzinski** [comment]
I’ve gotten the records loaded but I still can’t load the parts records.  They won’t validate.  I’ve also got a question about #20148 Calcite w/Sphalerite.  I used the “ A {string} “as Dusty suggested for the ID, but it looks strange to me (see snip)  Why is the “Calcite” barely legible below the “w/Sphalerite”?  I apologize if I’m driving you all crazy, but I’m being driven just as crazy, I can assure you!

Thanks, Mariel

[cid:image001.png@01D58E5C.874CA420]

**Comment by Jegelewicz** [comment]
>  used the “ A {string} “as Dusty suggested for the ID, but it looks strange to me (see snip)  Why is the “Calcite” barely legible below the “w/Sphalerite”?

That is how this formula presents. I just added an ID using the "A and B" formula, which I think does a better job of getting at what you want. Let me know if that works. You can delete either of the IDs and keep the one you want.

**Comment by Jegelewicz** [comment]
Can you provide a screenshot of what happens when you try to load the parts?

**Comment by mbprondzinski** [comment]
Yes, thanks Teresa, that looks much better.  I will use “A and B” from now on!

**Comment by mbprondzinski** [comment]
I have to go, but I will show you tomorrow.  I am editing the main record and re-entering the parts.  That works fine.

Laters!

**Comment by mbprondzinski** [comment]
Here is what they looked like in the specimen extras:

[cid:image001.png@01D58EFB.579FBEC0]

After deleting all but the one part I hadn’t entered into the record, I tried the bulkloader again. This time, I linked the GUID before validating and then validated the one remaining record that I didn’t enter manually in the catalog record and it validated!  Wouldn’t do that before…

[cid:image002.png@01D58F00.8CFF9630]

**Comment by Jegelewicz** [comment]
Well, I'm glad it all worked - although your images don't show up in GitHub.

Can you write down the steps for doing this?

> This time, I linked the GUID before validating

**Comment by Jegelewicz** [comment]
All changed with new interface.
